# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payload',
            old_name='type',
            new_name='payload_type',
        ),
        migrations.AlterField(
            model_name='payload',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
