# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180411_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='install_data',
            new_name='install_date',
        ),
    ]
