# Generated by Django 1.10 on 2016-09-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20160830_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='version',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
