# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-11 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180911_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_str',
        ),
    ]
