# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-11 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='content',
            field=models.BinaryField(),
        ),
    ]
