#!/usr/bin/python
import sys
import os
import subprocess
import stat
postflight_dir = '/usr/local/munki/postflight.d'
for script in os.listdir(postflight_dir):
    st = os.stat(os.path.join(postflight_dir, script))
    mode = st.st_mode
    if not mode & stat.S_IWOTH:
        try:
            subprocess.call([os.path.join(postflight_dir, script),
                            sys.argv[1]],
                            stdin=None)
        except OSError:
            print "Something went wrong!"
    else:
        print script + " is not executable or has bad permissions"