# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0040_machine_machine_model_friendly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_model',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_model_friendly',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='os_family',
            field=models.CharField(choices=[(b'Darwin', b'OS X'), (b'Windows', b'Windows'), (b'Linux', b'Linux')], db_index=True, default=b'Darwin', max_length=256, verbose_name=b'OS Family'),
        ),
    ]
