# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0041_auto_20160808_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginscriptrow',
            name='pluginscript_data',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pluginscriptrow',
            name='pluginscript_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pluginscriptsubmission',
            name='plugin',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
