# Generated by Django 1.10 on 2016-08-10 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0042_auto_20160808_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osquerycolumn',
            name='osquery_result',
        ),
        migrations.RemoveField(
            model_name='osqueryresult',
            name='machine',
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition_data',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fact',
            name='fact_data',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='fact_name',
            field=models.TextField(db_index=True),
        ),
        migrations.DeleteModel(
            name='OSQueryColumn',
        ),
        migrations.DeleteModel(
            name='OSQueryResult',
        ),
    ]
