# Generated by Django 1.10 on 2016-09-05 17:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0045_pluginscriptrow_submission_and_script_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginscriptrow',
            name='pluginscript_data_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pluginscriptrow',
            name='pluginscript_data_int',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pluginscriptrow',
            name='pluginscript_data_string',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
