# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0046_auto_20160905_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginscriptrow',
            name='pluginscript_data_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
