# Generated by Django 1.10 on 2016-09-09 11:59


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0047_manual_20160906_enableplugins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginscriptrow',
            name='pluginscript_data_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
