# Generated by Django 1.10 on 2017-02-17 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0048_auto_20160909_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact',
            name='fact_data',
            field=models.TextField(),
        ),
    ]
