# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0048_auto_20160909_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ohai',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False,
                                        auto_created=True, primary_key=True)),
                ('ohaiattribute_name', models.TextField()),
                ('ohaiattribute_data', models.TextField()),
            ],
            options={
                'ordering': ['ohaiattribute_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOhai',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False,
                                        auto_created=True, primary_key=True)),
                ('ohaiattribute_name', models.TextField()),
                ('ohaiattribute_data', models.TextField()),
                ('ohaiattribute_recorded',
                 models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['ohaiattribute_name', 'ohaiattribute_recorded'],
            },
        ),
        migrations.AddField(
            model_name='ohaiattribute',
            name='ohaiattribute_data',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='ohaiattribute',
            name='ohaiattribute_name',
            field=models.CharField(max_length=255, db_index=True),
        ),
        migrations.AddField(
            model_name='historicalohaiattribute',
            name='ohaiattribute_data',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='historicalohaiattribute',
            name='ohaiattribute_name',
            field=models.CharField(max_length=255, db_index=True),
        ),
    ]
