# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):


        migrations.CreateModel(
            name='Ohai',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ohai_name', models.TextField()),
                ('ohai_data', models.TextField()),
            ],
            options={
                'ordering': ['ohai_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOhai',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ohai_name', models.TextField()),
                ('ohai_data', models.TextField()),
                ('ohai_recorded', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['ohai_name', 'ohai_recorded'],
            },
        ),
