# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):


        migrations.CreateModel(
            name='Ohai',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ohaiattribute_name', models.TextField()),
                ('ohaiattribute_data', models.TextField()),
            ],
            options={
                'ordering': ['ohaiattribute_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalOhai',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ohaiattribute_name', models.TextField()),
                ('ohaiattribute_data', models.TextField()),
                ('ohaiattribute_recorded', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['ohaiattribute_name', 'ohaiattribute_recorded'],
            },
        ),
        migrations.AddField(
            model_name='historicalohaiattribute',
            name='machine',
            field=models.ForeignKey(to='server.ohaiattribute'),
        ),
        migrations.AddField(
            model_name='ohaiattribute',
            name='machine',
            field=models.ForeignKey(to='server.ohaiatrribute'),
        ),
