# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0049_auto_20170217_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='deployed',
            field=models.BooleanField(default=True),
        ),
    ]
