# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0050_machine_deployed'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='read_write',
            field=models.BooleanField(default=True),
        ),
    ]
