# Generated by Django 1.10 on 2017-06-24 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0051_apikey_read_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='read_write',
            field=models.BooleanField(default=False),
        ),
    ]
