# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0052_auto_20170624_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fact',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
