# Generated by Django 1.10 on 2017-08-22 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0056_machinedetailplugin_os_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinedetailplugin',
            name='os_family',
        ),
        migrations.AddField(
            model_name='machinedetailplugin',
            name='os_families',
            field=models.CharField(db_index=True, default=b'Darwin',
                                   max_length=256, verbose_name=b'OS Family'),
        ),
    ]
