# Generated by Django 1.10 on 2018-01-18 19:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0059_machine_report_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='broken_client',
            field=models.BooleanField(default=False),
        ),
    ]
