# Generated by Django 1.10 on 2018-02-12 18:19


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0062_auto_20180212_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinedetailplugin',
            name='type',
        ),
    ]
