# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-16 13:49
from __future__ import unicode_literals
import json
import os

from django.db import migrations


def add_default_sal_settings(apps, schema_editor):
    """Add in missing default settings to database."""
    # Get historical SalSettings.
    SalSetting = apps.get_model('server', "SalSetting")
    default_sal_settings = get_defaults()
    for setting in default_sal_settings:
        _, created = SalSetting.objects.get_or_create(
            name=setting['name'], defaults={'value': setting['value']})
        if created:
            print "Created Sal Setting: '{name}' with value: '{value}'.".format(**setting)


def reverse_default_sal_settings(apps, schema_editor):
    """We don't care if the default settings are left in the database."""
    pass


def get_defaults():
    """Get the default settings from our defaults file."""
    # The file is stored in the project root /sal folder.
    default_sal_settings_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "../../sal", 'default_sal_settings.json')
    with open(default_sal_settings_path) as handle:
        default_sal_settings = json.load(handle)

    return default_sal_settings


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0063_remove_machinedetailplugin_type'),
    ]

    operations = [
        migrations.RunPython(add_default_sal_settings, reverse_default_sal_settings),
    ]
