# Generated by Django 1.10 on 2018-02-19 08:57


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0064_clean_friendly_names'),
        ('server', '0064_auto_20180216_1349'),
    ]

    operations = [
    ]
