# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0067_auto_20180313_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinedetailplugin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plugin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
    ]
