# Generated by Django 1.11 on 2018-04-20 17:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0068_auto_20180313_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='install_log',
        ),
    ]
