# Generated by Django 1.11 on 2018-04-25 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0070_remove_machine_install_log_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatehistory',
            name='pending_recorded',
        ),
    ]
