# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0069_manual_dump_friendly_names'),
        ('server', '0073_remove_machine_report_format'),
    ]

    operations = [
    ]
