# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0074_merge_20180621_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='activity',
            field=models.BooleanField(default=False),
        ),
    ]
