# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-23 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0076_remove_blank_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyNameCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_stub', models.CharField(db_index=True, max_length=5)),
                ('friendly_name', models.CharField(max_length=255)),
            ],
        ),
    ]
