# Generated by Django 1.10 on 2018-07-23 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0077_friendlynamecache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='private_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='public_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fact',
            name='fact_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='friendlynamecache',
            name='serial_stub',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalfact',
            name='fact_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfact',
            name='fact_recorded',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='installedupdate',
            name='update_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendingappleupdate',
            name='update_version',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pendingupdate',
            name='update_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pluginscriptrow',
            name='pluginscript_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pluginscriptrow',
            name='pluginscript_data_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pluginscriptrow',
            name='pluginscript_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pluginscriptrow',
            name='submission_and_script_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pluginscriptsubmission',
            name='plugin',
            field=models.CharField(max_length=255),
        ),
    ]
