# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-12 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0078_auto_20180723_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='report',
            field=models.BinaryField(null=True),
        ),
    ]
