# Generated by Django 2.1.4 on 2019-02-02 15:20

from django.db import migrations, models
import django.db.models.deletion
import ulid2


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0079_auto_20181211_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedItem',
            fields=[
                ('id', models.UUIDField(default=ulid2.generate_ulid_as_uuid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_managed', models.DateTimeField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('PENDING', 'Pending'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=7)),
                ('data', models.TextField(null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementSource',
            fields=[
                ('id', models.UUIDField(default=ulid2.generate_ulid_as_uuid, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='manageditem',
            name='management_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ManagementSource'),
        ),
    ]
