# Generated by Django 2.1.4 on 2019-02-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0080_auto_20190202_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='management_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='server.ManagementSource'),
        ),
        migrations.AddField(
            model_name='historicalfact',
            name='management_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historical_facts', to='server.ManagementSource'),
        ),
    ]
