# Generated by Django 2.1.4 on 2019-02-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0081_auto_20190204_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manageditem',
            unique_together={('machine', 'name', 'management_source')},
        ),
    ]
