# Generated by Django 2.1.4 on 2019-02-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0083_auto_20190215_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='machine',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
