# Generated by Django 2.1.4 on 2019-02-28 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0084_auto_20190228_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_type', models.CharField(choices=[('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug'), ('OTHER', 'Other')], default='OTHER', max_length=7)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='server.Machine')),
                ('management_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='server.ManagementSource')),
            ],
        ),
    ]
