# Generated by Django 2.1.4 on 2019-03-01 19:24

from django.db import migrations, models
import django.db.models.deletion
import ulid2


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0086_auto_20190228_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedItemHistory',
            fields=[
                ('id', models.UUIDField(default=ulid2.generate_ulid_as_uuid, primary_key=True, serialize=False)),
                ('recorded', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('PENDING', 'Pending'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=7)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Machine')),
                ('management_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ManagementSource')),
            ],
            options={
                'ordering': ['-recorded'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='manageditemhistory',
            unique_together={('machine', 'name', 'management_source', 'recorded')},
        ),
    ]
