# Generated by Django 2.1.4 on 2019-03-04 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0088_auto_20190304_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='report',
        ),
    ]
