# Generated by Django 2.1.4 on 2019-03-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0089_remove_machine_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='last_puppet_run',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='puppet_errors',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='puppet_version',
        ),
    ]
