# Generated by Django 2.1.4 on 2019-03-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0090_auto_20190305_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='activity',
        ),
    ]
