# Generated by Django 2.1.4 on 2019-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0092_auto_20190305_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('OTHER', 'Other'), ('DEBUG', 'Debug')], default='OTHER', max_length=7),
        ),
    ]
