# Generated by Django 2.1.4 on 2019-09-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0093_auto_20190318_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageditem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
