# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 11:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import search.current_user


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='created_by',
            field=models.ForeignKey(default=search.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.CharField(default='Unsaved Search 2016-10-19 11:44:07.660268+00:00', max_length=100),
        ),
    ]
