# Generated by Django 1.10 on 2016-10-19 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20161019_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrow',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.CharField(
                default='Unsaved Search 2016-10-19 13:57:19.564127+00:00', max_length=100),
        ),
    ]
