# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20161019_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrow',
            name='search_field',
            field=models.CharField(default='1', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(
                default='Unsaved Search 2016-10-19 15:13:36.513443+00:00', max_length=100),
        ),
    ]
