# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20161031_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(
                default='Unsaved Search 2016-10-31 12:40:51.143273+00:00', max_length=100),
        ),
    ]
