# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-10 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20170223_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(
                default='Unsaved Search 2017-08-10 19:05:53.135973+00:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchfieldcache',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searchgroup',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searchrow',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
