# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20170223_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(default='Unsaved Search 2017-05-16 18:52:07.119443+00:00', max_length=100),
        ),
    ]
