# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-19 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20170822_1207'),
        ('search', '0011_auto_20170516_1952'),
    ]

    operations = [
    ]
