# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0060_machine_broken_client'),
        ('search', '0012_auto_20170822_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('search_item', models.TextField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Machine')),
            ],
        ),
    ]
