# Generated by Django 2.1.4 on 2019-02-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_auto_20180426_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchfieldcache',
            name='search_model',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Facter', 'Facter'), ('External Script', 'External Script'), ('Application Inventory', 'Application Inventory'), ('Application Version', 'Application Version')], default='AND', max_length=254, verbose_name='Search item'),
        ),
        migrations.AlterField(
            model_name='searchrow',
            name='search_models',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Facter', 'Facter'), ('External Script', 'External Script'), ('Application Inventory', 'Application Inventory'), ('Application Version', 'Application Version'), ('Profile', 'Profile'), ('Profile Payload', 'Profile Payload')], default='AND', max_length=254, verbose_name='Search item'),
        ),
    ]
